### ISSUE TITLE
Not working with Moodle version 3.6

### ISSUE THREAD

**Issue by sangeeyeah** [Paytm-Payments/Paytm_Moodle_Kit#3]
The Paytm plugin is not working with the new stable release Moodle 3.6. 

The payment is initiated and can be successfully completed; but when the user is returned to "/enrol/paytm/itn.php" , the error message states "This page isn’t working
somedomainname.com is currently unable to handle this request."

So, the automatic enrollment after payment doesn't happen.

**Comment by sangeeyeah** [comment]
@Prabhat1Mishra @rahul7verma - Hi Team, The Paytm Moodle Plugin works perfectly with the 3.5 version of Moodle, however with the release of the version 3.6, the plugin does not work anymore. 

The payment is initiated and can be successfully completed; but when the user is returned to "/enrol/paytm/itn.php" , the error message states "This page isn’t working
somedomainname.com is currently unable to handle this request." So, the automatic enrollment after payment doesn't happen.

Should be a relatively minor fix. Can you please look into it. Since Moodle v3.6 comes with a number of security fixes and performance improvements, please help Paytm users to upgrade.

**Comment by Prabhat1Mishra** [comment]
@sangeeyeah 

Hello Sangeeyeah,

Sorry for the delay, and the stable code according to latest version 3.6 is updated on GitHub.
Please check and confirm.

**Comment by sangeeyeah** [comment]
**@Prabhat1Mishra** 

I have tested the updated plugin with Moodle version 3.6 and the status is as follows:

**Current flow:**
1. Transaction gets initiated successfully.
2. Payment gets processed
3. The flow comes back to 'itn.php' and gets stuck with a blank screen

**What is happening in the back-end.**
1. User is successfully getting enrolled in the course

**What should also happen - to restore full functionality of the plugin**
1. The 'itn.php' should get redirected to the enrolled course page
2. The email confirmations (to teacher / admin / student) should also get triggered

Since the enrollment is now successfully happening, only the notification email triggers + the redirect back to the course are not working.

Thank you for looking into this.

**Comment by sangeeyeah** [comment]
@LalitChaudhary1 Thank you for the update. I am installing v3.6 on a test server and will test out the updated plugin on 3.6 / 3.7 and post the results here in a couple of days.

**Comment by gurujiathome** [comment]
nice work

**Comment by sangeeyeah** [comment]
@LalitChaudhary1 Tested with 3.6 and the plugin is stable and functions as required. Thanks!

**Comment by malkarisreenivasulu** [comment]
It's not working for internet banking, debit and credit card,  working only with UPI,  am getting blank white page. please help
